FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip -r requirements.txt

COPY . .

ENV FLASK_APP qlerner
ENV FLASK_ENV development

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
