FROM python:3.12.0a5-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip -r requirements.txt

COPY . .

ENV FLASK_APP qlerner

# generate templates and initiate db
RUN python jinja.py && flask --app qlerner init-db
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
